/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DistributorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.RecyclePlant.DistributionCentreOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DistributorWorkRequest;
import Business.WorkQueue.GradingOfficerWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.GradingOfficerRole.DisapprovedMaterialsJPanel1;
import userinterface.TransformManagerRole.TransformationJPanel;

/**
 *
 * @author singh
 */
public class DistributorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DistributorWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private DistributionCentreOrganization organization;
    private Enterprise enterprise;
    private TransformationJPanel transformationJPanel;
    public DistributorWorkArea(JPanel userProcessContainer, UserAccount account, DistributionCentreOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (DistributionCentreOrganization) organization;
        this.enterprise = enterprise;
        populateTable();
    }
    public void populateTable(){
             DefaultTableModel dtm = (DefaultTableModel)gradingOffice_tbl.getModel();
        dtm.setRowCount(0);
      for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            if(request.getSender() != null){
                Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getUsername();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getUsername();
            row[3] = request.getStatus();
            
            dtm.addRow(row);
            }
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gradingOffice_tbl = new javax.swing.JTable();
        viewList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        assignJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 231, 226));

        gradingOffice_tbl.setBackground(new java.awt.Color(204, 255, 204));
        gradingOffice_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Source", "Sender", "Reciever", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gradingOffice_tbl);

        viewList.setBackground(new java.awt.Color(0, 204, 153));
        viewList.setText("View List");
        viewList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Distributor Work Area");

        assignJButton.setBackground(new java.awt.Color(0, 204, 153));
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(assignJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(viewList, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewList, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListActionPerformed
        int selectedRow = gradingOffice_tbl.getSelectedRow();
        if (selectedRow < 0){
           JOptionPane.showMessageDialog(null, "Please select a row");

        }
        
        DistributorWorkRequest request = (DistributorWorkRequest)gradingOffice_tbl.getValueAt(selectedRow, 0);
        ViewEndProducts disapprovedMaterialsJPanel1 = new ViewEndProducts(userProcessContainer,request, account,selectedRow,enterprise);
        userProcessContainer.add("ViewEndProducts", disapprovedMaterialsJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewListActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        gradingOffice_tbl.setColumnSelectionAllowed(true);
        int selectedRow = gradingOffice_tbl.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        else if(gradingOffice_tbl.getValueAt(selectedRow, 3).equals("Distributed")){
            JOptionPane.showMessageDialog(null, "This task has been completed, please select another task");
        }
        else
        {

        WorkRequest request = (WorkRequest)gradingOffice_tbl.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Distributed");
        organization.getWorkQueue().getWorkRequestList().remove(selectedRow);
        organization.getWorkQueue().getWorkRequestList().add(request);
        populateTable();
        }
    }//GEN-LAST:event_assignJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTable gradingOffice_tbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewList;
    // End of variables declaration//GEN-END:variables
}
